@startuml
actor usuario_encargado
boundary MenuEncargado
control Encargado
entity RepoProducto
entity RepoCategoría
usuario_encargado -> MenuEncargado: Selecciona Productos
activate MenuEncargado
MenuEncargado --> usuario_encargado: Muestra el menú de productos
usuario_encargado -> MenuEncargado: Selecciona Cargar Nuevo Producto
MenuEncargado --> usuario_encargado: Solicita datos
usuario_encargado -> MenuEncargado: Ingresa datos
MenuEncargado -> Encargado: Valida datos
activate Encargado
Encargado -> RepoCategoría: Busca categoría
activate RepoCategoría
RepoCategoría --> Encargado: Devuelve información
deactivate RepoCategoría
Encargado -> RepoProducto: Carga nuevo producto
activate RepoProducto
RepoProducto --> Encargado: Confirma
deactivate RepoProducto
Encargado --> MenuEncargado: Confirma operación
deactivate Encargado
MenuEncargado --> usuario_encargado: Muestra mensaje de confirmación
deactivate MenuEncargado
@enduml