@startuml
actor usuario_encargado
boundary MenuEncargado
control Encargadoo
entity RepoProveedor
entity RepoCategoría
usuario_encargado -> MenuEncargado: Selecciona Proveedores
activate MenuEncargado
MenuEncargado --> usuario_encargado: Muestra el menú de Proveedores
usuario_encargado -> MenuEncargado: Selecciona Cargar Nuevo Proveedor
MenuEncargado --> usuario_encargado: Solicita datos
usuario_encargado -> MenuEncargado: Ingresa datos
MenuEncargado -> Encargadoo: Valida datos
activate Encargadoo
Encargadoo -> RepoCategoría: Busca categoría
activate RepoCategoría
RepoCategoría --> Encargadoo: Devuelve información
deactivate RepoCategoría
Encargadoo -> RepoProveedor: Carga nuevo Proveedor
activate RepoProveedor
RepoProveedor --> Encargadoo: Confirma
deactivate RepoProveedor
Encargadoo --> MenuEncargado: Confirma operación
deactivate Encargadoo
MenuEncargado --> usuario_encargado: Muestra mensaje de confirmación
deactivate MenuEncargado
@enduml