@startuml
actor usuario_encargado
boundary MenuEncargado
control Encargado
entity RepoCategoria
usuario_encargado -> MenuEncargado: Selecciona Categorias
activate MenuEncargado
MenuEncargado --> usuario_encargado: Muestra el menú de Categorias
usuario_encargado -> MenuEncargado: Selecciona Cargar Nueva Categoria
MenuEncargado --> usuario_encargado: Solicita datos
usuario_encargado -> MenuEncargado: Ingresa datos
MenuEncargado -> Encargado: Valida datos
activate Encargado
deactivate RepoCategoria
Encargado -> RepoCategoria: Carga nueva Categoria
activate RepoCategoria
RepoCategoria --> Encargado: Confirma
deactivate RepoCategoria
Encargado --> MenuEncargado: Confirma operación
deactivate Encargado
MenuEncargado --> usuario_encargado: Muestra mensaje de confirmación
deactivate MenuEncargado
@enduml