@startuml
actor usuario_empleado
boundary MenuEmpleado
control Empleado
entity RepoProducto
entity RepoVenta
entity RepoProveedor


usuario_empleado -> MenuEmpleado: Selecciona Registrar Venta
activate MenuEmpleado
loop n productos
MenuEmpleado -> usuario_empleado: Solicita nombre del producto
usuario_empleado -> MenuEmpleado: Ingresa nombre del producto
MenuEmpleado -> Empleado: Valida existencia del producto
activate Empleado
Empleado -> RepoProducto: Consultar producto
activate RepoProducto
RepoProducto --> Empleado: Devuelve Información
deactivate RepoProducto
Empleado --> MenuEmpleado: Confirma existencia
MenuEmpleado -> usuario_empleado: Solicita cantidad
usuario_empleado -> MenuEmpleado: Ingresa cantidad
MenuEmpleado -> Empleado: Valida stock
Empleado --> MenuEmpleado: Confirma disponibilidad
deactivate Empleado
MenuEmpleado --> usuario_empleado: Muestra mensaje de aceptación
end

usuario_empleado -> MenuEmpleado: Selecciona Finalizar
MenuEmpleado --> usuario_empleado: Muestra detalle de venta
MenuEmpleado -> usuario_empleado: Solicita correo electrónico del cliente
usuario_empleado -> MenuEmpleado: Ingresa correo electronico
MenuEmpleado -> Empleado: Valida correo electrónico
activate Empleado
Empleado --> MenuEmpleado: Confirma correo electrónico
MenuEmpleado -> usuario_empleado: Solicita confirmación de venta
usuario_empleado -> MenuEmpleado: Confirma la venta
MenuEmpleado -> Empleado: Actualiza información
Empleado -> RepoVenta: Carga nueva venta
activate RepoVenta
RepoVenta --> Empleado: Confirma
deactivate RepoVenta
loop n productos
Empleado -> RepoProducto: Actualiza stock
activate RepoProducto
RepoProducto --> Empleado: Confirma
Empleado -> Empleado: Verifica limite minimo
  alt#Gold #LightGreen alcanza limite minimo

  Empleado -> RepoProveedor: Consultar Proveedor
  RepoProveedor --> Empleado: Devuelve informacion
  Empleado -> Empleado: Envia pedido al proveedor
 end
deactivate RepoProducto
end

Empleado -> Empleado: Envia correo de confirmación al cliente
Empleado --> MenuEmpleado: Confirma operación
deactivate Empleado
MenuEmpleado --> usuario_empleado: Muestra mensaje de confirmación

deactivate MenuEmpleado
@enduml